### ISSUE TITLE
Security group rules for worker nodes when octavia_provider is OVN

### ISSUE THREAD

**Issue by gabriel-samfira** [vexxhost/magnum-cluster-api#479]
Hi folks,

According to https://cluster-api-openstack.sigs.k8s.io/clusteropenstack/configuration.html#security-groups, when OVN is used as a load balancer, the following spec needs to be used:

```yaml
managedSecurityGroups:
  workerNodesSecurityGroupRules:
  - remoteIPPrefix: 0.0.0.0/0
    direction: ingress
    etherType: IPv4
    name: Node Port (TCP, anywhere)
    portRangeMin: 30000
    portRangeMax: 32767
    protocol: tcp
  - remoteIPPrefix: 0.0.0.0/0
    direction: ingress
    etherType: IPv4
    name: Node Port (UDP, anywhere)
    portRangeMin: 30000
    portRangeMax: 32767
    protocol: udp
```

Right now, there is no connectivity when using OVN as a load balancer.
