### ISSUE TITLE
Resizing a node group with cluster autoscaling enabled

### ISSUE THREAD

**Issue by MaximMonin** [vexxhost/magnum-cluster-api#521]
Related to: https://github.com/vexxhost/magnum-cluster-api/issues/243
Related to: https://github.com/kubernetes/autoscaler/issues/5267

**Issue**
A cluster without autoscaling has the ability to change the number of nodes in ng using a resize operation. A cluster with autoscaling enabled has limited the ability to change the number of nodes in ng. I should be able to change the min-max autoscaling range to any new values. Right now Magnum Cluster API allows you to set a new min and max node count in one step, but Magnum API does not allow you to set the min and max node count if the current node count is outside the min and max range.
This leads to restriction to resizing any group in autoscaling enabled cluster. For example I am creating default-worker group with 3 nodes (min=max=3) and want to resize it to 1-1 (1-2) or to 5-5 (5-10). The only way to scale it down is setup 1-3 range, wait 10-15 minutes until cluster deletes its nodes and then change it to 1-1. The only way to scale up nodes is to set 3-5 range.

**Bypassing magnum api restriction**
Magnum api + current magnum cluster api driver has a way to change min-max range to any values:
1. node_count (3) > new max_node_count (1)
```
* patch v1/clusters/{cluster_id}/nodegroups/{group_id} { [ { "op": "replace", "path": "/min_node_count", "value": 1 }, { "op": "replace", "path": "/max_node_count", "value": 3 } ] }
* post v1/clusters/{cluster_id}/actions/resize { "node_count": 1, "nodegroup": "{group_id}" }
* patch v1/clusters/{cluster_id}/nodegroups/{group_id} { [ { "op": "replace", "path": "/min_node_count", "value": 1 }, { "op": "replace", "path": "/max_node_count", "value": 1 } ] }
```
2. node_count (3) < new min_node_count (5):
```
* patch v1/clusters/{cluster_id}/nodegroups/{group_id} { [ { "op": "replace", "path": "/min_node_count", "value": 3 }, { "op": "replace", "path": "/max_node_count", "value": 5 } ] }
* post v1/clusters/{cluster_id}/actions/resize { "node_count": 5, "nodegroup": "{group_id}" }
* patch v1/clusters/{cluster_id}/nodegroups/{group_id} { [ { "op": "replace", "path": "/min_node_count", "value": 5 }, { "op": "replace", "path": "/max_node_count", "value": 5 } ] }
```

By checking the cluster topology, we can determine that the cluster has valid new annotations (new min-max range). BUT cluster nodes wil be the same (3), and this value never change.

** Autoscaler **
according to https://github.com/kubernetes/autoscaler/issues/5267#issuecomment-1292092830 it is known behavior in the autoscaler, if your node group is below the minimum, or above the maximum, the autoscaler will not attempt to reach the minimum or maximum, respectively.
Tests with scale down shows: autoscaler has min: 1, max: 1, replica: 3... during 10-15 minutes tries to delete node and fails with "cannot scale down to 2 nodes because 2 nodes more than max node count"
Tests with scale up shows: autoscaler has min:5, max:5, replica: 3 (nothing to do)

** Solution **
Autoscaler helm charm has many options. One of options is:
```
# extraArgs -- Additional container arguments.
# Refer to https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca for the full list of cluster autoscaler
# parameters and their default values.
# Everything after the first _ will be ignored allowing the use of multi-string arguments.
extraArgs:
  logtostderr: true
  stderrthreshold: info
  v: 4
  # write-status-configmap: true
  # status-config-map-name: cluster-autoscaler-status
```
we can add new extraArgs enforce-node-group-min-size=true
```
extraArgs:
  logtostderr: true
  stderrthreshold: info
  v: 4
  enforce-node-group-min-size: true
```
with this flag the autoscaler will scale up nodes immediately if node_count < min_node_count.
