### ISSUE TITLE
feature: custom preKubeadmCommands per node pool

### ISSUE THREAD

**Issue by fitbeard** [vexxhost/magnum-cluster-api#722]
Sometimes user needs to change/tune something per node pool. Reasons for this can be very different - hardware specific, workload tuning.

AWS EKS has option to pass such as thing using pool profile.

```
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: md-a-config
spec:
  template:
    spec:
      preKubeadmCommands:
        - sysctl -w kernel.core_pattern="|/bin/false"
        - echo 'kernel.core_pattern="|/bin/false"' >> /etc/sysctl.conf
```
